image: ruby:2.5

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
  - vendor/bundle/ruby

variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"

before_script:
  - bundle install -j $(nproc) --path vendor/bundle

pages:
  script:
  - 'echo "commit-sha: $CI_COMMIT_SHA" > _commit_sha.yml'
  - bundle exec jekyll build -d public --config _config.yml,_config_gitlab.yml,_commit_sha.yml
  artifacts:
    paths:
    - public

