image: ruby:2.4

cache:
  paths:
    - vendor/

before_script:
  - bundle install --path vendor

pages:
  script:
  - bundle exec jekyll build -d public --config _config.yml,_config_gitlab.yml
  artifacts:
    paths:
    - public

