title:            'Andy Massimino'
description:      'Andy Massimino''s personal website'
# url:              'https://andymass.github.io'
baseurl:
canonical_url:    'https://normed.space'
google_analytics: UA-64739852-1

external:
  github: 'https://github.com/andymass/'
  scholar: 'https://scholar.google.com/citations?user=7_MQJy4AAAAJ'
  arxiv: 'https://arxiv.org/search/?searchtype=author&query=Massimino%2C+A+K'
  linkedin: 'https://www.linkedin.com/in/amassive'
  orcid: 'https://orcid.org/0000-0002-0484-875X'

# cvurl: '/cv'

copyyear: '2017&#x2012;2018'

plugins:
  - jekyll-redirect-from

repository: 'andymass/andymass.github.io'

bibloc: 'https://raw.githubusercontent.com/andymass/andymass.github.io/master'

permalink:        /posts/:categories/:title/

defaults:
  - values:
      layout: "default"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: nil

highlighter: rouge

